using System.Collections.Immutable;
using QaaS.Framework.SDK.Hooks.Generator;
using QaaS.Framework.SDK.Session.DataObjects;
using QaaS.Framework.SDK.Session.SessionDataObjects;
using QaaS.Framework.Serialization.Deserializers;
using QaaS.Framework.Serialization.Serializers;

namespace QaaS.Framework.SDK.DataSourceObjects;

/// <summary>
/// Represents the data produced by a data source from a generator generically casted
/// </summary>
public record DataSource
{
    /// <summary>
    /// The name of the data source used to identify it
    /// </summary>
    public string Name { get; init; } = null!;

    /// <summary>
    /// Whether the data generated by this data source is generated lazily or not
    /// </summary>
    public bool Lazy { get; init; }

    /// <summary>
    /// The list of data sources relevant to the data source
    /// </summary>
    public IImmutableList<DataSource> DataSourceList { get; set; } = null!;

    /// <summary>
    /// The data source's generator
    /// </summary>
    public IGenerator Generator { get; set; } = null!;

    /// <summary>
    /// The Serializer that will serialize the generated data, null means no serialization.
    /// </summary>
    private readonly ISerializer? _serializer;

    public ISerializer? Serializer
    {
        get => _serializer;
        init
        {
            if (value is not null && _deserializer is not null)
                throw new InvalidOperationException(
                    $"{nameof(DataSource)} object can't have both Serializer and Deserializer");
            _serializer = value;
        }
    }

    /// <summary>
    /// The Deserializer that will deserialize the generated data, null means no deserialization.
    /// </summary>
    private readonly IDeserializer? _deserializer;

    public IDeserializer? Deserializer
    {
        get => _deserializer;
        init
        {
            if (value is not null && _serializer is not null)
                throw new InvalidOperationException(
                    $"{nameof(DataSource)} object can't have both Serializer and Deserializer");
            _deserializer = value;
        }
    }

    /// <summary>
    /// A Specific type that the deserializer will deserialize the data to.
    /// </summary>
    private readonly Type? _deserializerSpecificType;

    public Type? DeserializerSpecificType
    {
        get => _deserializerSpecificType;
        init
        {
            if (value is not null && _deserializer is null)
                throw new InvalidOperationException(
                    $"{nameof(DataSource)} object can have {nameof(DeserializerSpecificType)} only if it has Deserializer");
            _deserializerSpecificType = value;
        }
    }

    /// <summary>
    /// If data is generated not lazily, save it after first data source so future data sources
    /// don't generate it again from scratch
    /// </summary>
    private IList<Data<object>>? _generatedData = null;

    /// <summary>
    /// Retrieves this data source's data according to the data source's values
    /// </summary>
    /// <param name="ranSessionsDataList"> A list of the data of sessions already ran before this data source was
    /// called, by default no sessions are passed </param>
    /// <returns> The retrieved data from this data source </returns>
    public IEnumerable<Data<object>> Retrieve(IImmutableList<SessionData>? ranSessionsDataList = null)
    {
        // If data source is not configured as lazy and the data was already generated once before,
        // return the already generated data
        if (!Lazy && _generatedData != null) return _generatedData;
        
        ranSessionsDataList ??= Array.Empty<SessionData>().ToImmutableList();
        var generatedData =
            Generator.Generate(ranSessionsDataList, DataSourceList) ??
            throw new ArgumentNullException(Generator.GetType().Name, 
                $"Data generated in data source {Name} by generator {Generator.GetType().Name} is null");

        // If Serializer has been configured, serialize the data
        // If a data's specific serializer has been configured, serialize the data with the specific serializer
        if (_serializer != null)
        {
            generatedData = generatedData.Select(data =>
            {
                var serializer = data.MetaData?.Serializer ?? _serializer;
                return new Data<object>
                {
                    MetaData = data.MetaData,
                    Body = serializer.Serialize(data.Body)
                };
            });
        }
        
        // If Deserialize has been configured, deserialize the data into the configured type
        // If a data's specific deserializer has been configured, deserialize the data with the specific deserializer
        if (_deserializer != null)
        {
            generatedData = generatedData.Select((data, index) =>
            {
                var deserializer = data.MetaData?.Deserializer ?? _deserializer;
                if (data.Body is not (byte[] or null))
                    throw new InvalidOperationException(
                        $"Data at index {index} generated in data source {Name}" +
                        $" by generator {Generator.GetType().Name} is of type {data.Body?.GetType().Name}" +
                        $" and not byte[], cannot be deserialized.");
            
                return new Data<object>
                {
                    MetaData = data.MetaData,
                    Body = deserializer.Deserialize((byte[]?)data.Body, _deserializerSpecificType) 
                };
            });
        }
        
        // If data source is configured as lazy return the new generated data on every `Retrieve` call
        if (Lazy) return generatedData;

        _generatedData = generatedData.ToList();
        return _generatedData;
    }
}