name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Restore
        run: dotnet restore QaaS.Framework.sln
      - name: Build
        run: dotnet build QaaS.Framework.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test QaaS.Framework.sln --no-build --no-restore --configuration Release

  pack-push:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Restore
        run: dotnet restore QaaS.Framework.sln
      - name: Build
        run: dotnet build QaaS.Framework.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test QaaS.Framework.sln --no-build --no-restore --configuration Release
      - name: Pack
        run: |
          TAG_VERSION=${{ github.ref_name }}
          # Remove leading 'v' if present
          TAG_VERSION_CLEAN=${TAG_VERSION#v}
          dotnet pack QaaS.Framework.sln --configuration Release --no-build --output ./packages --version $TAG_VERSION_CLEAN
      - name: Push NuGet
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/"
