name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CONFIGURATION: Release
  PROJECT_PATH: QaaS.Framework.sln
  PACKAGE_OUTPUT_DIRECTORY: ./artifacts
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.CONFIGURATION }}

  test:
    name: Test
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Test solution
        run: dotnet test ${{ env.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore --maxcpucount

  deploy:
    name: Deploy
    runs-on: windows-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.CONFIGURATION }}

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Validate SemVer tag
        shell: bash
        run: |
          VERSION="${{ steps.version.outputs.version-without-v }}"
          # Regex Breakdown:
          # ^[0-9]+\.[0-9]+\.[0-9]+  -> Matches X.X.X
          # (-(alpha|beta)\.[0-9]+)? -> OPTIONAL: hyphen, then "alpha" or "beta", then dot, then digits
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)\.[0-9]+)?$ ]]; then
            echo "Error: '$VERSION' is not a valid version."
            echo "Allowed formats: X.X.X, X.X.X-alpha.N, or X.X.X-beta.N"
            exit 1
          fi

      - name: Pack project
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration ${{ env.CONFIGURATION }} --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ vars.NUGET_SOURCE_URL }} # don't skip duplicate purposely
